In [2]:
# imports
import requests as re
import os
import pandas as pd
import numpy as numpy
import sqlite3

In [3]:
fs_key = os.environ["foursquare_api"]
yelp_key = os.environ["yelp_api"]
google_key = os.environ["google_api"]

# Foursquare

Send a request to Foursquare with a small radius (1000m) with the location of your choice

In [4]:
url = f'https://api.foursquare.com/v3/places/search?ll=51.03798628905197,-114.08773188686932&radius=1000&categories=13065&fields=name,location,rating,stats&limit=50'
headers = {
    "Accept": "application/json",
    "Authorization": fs_key
}

In [5]:
res = re.request("GET", url, headers=headers)

In [11]:
fs_res = res.json()

8.7

In [22]:
fs_dict = {'name': [],
           'address': [],
           'rating': [],
          'total ratings': []}

for result in fs_res['results']:
    name_value = result['name']
    fs_dict['name'].append(name_value)
    address_value = result['location']['address']
    fs_dict['address'].append(address_value)
    try:
        rating_value = result['rating']
        rating_value = float(rating_value)
        fs_dict['rating'].append(rating_value)
        t_ratings_value = result['stats']['total_ratings']
    except:
        fs_dict['rating'].append(0)
    t_ratings_value = int(t_ratings_value)
    fs_dict['total ratings'].append(t_ratings_value)

Parse through the response to get the POI details you want (rating, name, location, etc)

In [23]:
fs_dict

{'name': ['Galaxie Diner',
  'Rustic Sourdough Bakery',
  'Blanco Cantina',
  'Caffe Beano',
  'Anejo',
  'Holy Grill',
  'Trolley 5 Restaurant and Brewery',
  'Analog Coffee',
  'Bridgette Bar',
  'Jamesons Irish Pub',
  'Sucre Patisserie & Cafe',
  'Ship & Anchor Pub',
  'Bonterra Trattoria',
  'Casbah Restaurant',
  'Good Earth Cafe',
  'Thai Tai',
  'Pig & Duke Neighbourhood Pub',
  'Philosafy Coffee',
  'Golden Bell Saigon Restaurant',
  'Boudoir Rouge',
  'National Beer Hall',
  'World Bier Haus 1410',
  'Midori Japanese Cafe',
  "Popeye's Louisiana Kitchen",
  'A&W Restaurant',
  'Mugs Restaurant & Pub',
  'Fire N Ice',
  "Watchman's Pub & Eatery",
  "King's Chinese Food",
  'Donna Mac',
  'Lounge Eighteen',
  'Tim Hortons',
  'Trio Restaurant & Cafe',
  'Ke Charcoal Grill & Sushi',
  'Société Coffee Lounge',
  "Domino's Pizza",
  "Phil's on 11th",
  'Alumni Sandwich & Liquor Bar',
  "Ben's Cafe",
  'Una Takeaway',
  'Wakado Ramen',
  "McDonald's",
  'Comery Block Barbecue',
  "Ranchmen's Club",
  '5S17',
  'Max Pasley Enterprises Ltd',
  'Los Chilitos Taco & Tequila House',
  'Tsuki Izakaya',
  "Sultan's Tent",
  'Manie S Pizzeria & Greek Csne'],
 'address': ['1413 11th St SW',
  '1305 17 Ave SW',
  '723 17 Ave SW',
  '1613 9 St SW',
  '723 17 Ave SW',
  '827 10 Ave SW',
  '728 17 Ave SW',
  '740 17 Ave SW',
  '739 10 Ave SW',
  '1230 17th Ave SW',
  '1007 8 St SW',
  '534 17 Ave SW',
  '1016 8 St SW',
  '720 11 Ave SW',
  '1502 11 St SW',
  '615 17th Ave SW',
  '1312 12 Ave SW',
  '632 17 Ave SW',
  '1112 17 Ave SW',
  '907 9 Ave SW',
  '550 17 Ave SW',
  '1410 17 Ave SW',
  '1054 17 Ave SW',
  '1304 17 Ave SW',
  '1320 14 St SW',
  '1330 15 Ave SW',
  '854 16 Ave SW',
  '1109 17 Ave SW',
  '1050 17 Ave SW',
  '1002 9 St SW',
  '1005 17 Ave SW',
  '539 17 Ave SW',
  '1504 16 Ave SW',
  '1501 15 Ave SW',
  '1223 11 Ave SW',
  '1230 8 St SW',
  '1239 11 Ave SW',
  '725 17 Ave SW',
  '909 11 Ave SW',
  '616 17 Ave SW',
  '907 10 Ave SW',
  '1422 17 Ave SW',
  '638 17 Ave SW',
  '710 13 Ave SW',
  '634A 17th Ave SW',
  '1032 17 Ave SW',
  '1309 17 Ave SW',
  '908 17 Ave SW',
  '909 17 Ave SW',
  '907 17 Ave NW'],
 'rating': [8.7,
  8.5,
  8.8,
  7.9,
  8.5,
  8.9,
  8.2,
  8.0,
  8.4,
  7.4,
  8.0,
  8.3,
  8.0,
  8.1,
  7.1,
  7.9,
  7.6,
  7.8,
  6.9,
  7.6,
  7.6,
  7.1,
  6.4,
  6.5,
  6.7,
  6.6,
  6.5,
  5.9,
  0,
  6.2,
  0,
  6.3,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  5.0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 'total ratings': [93,
  12,
  36,
  89,
  132,
  85,
  52,
  184,
  29,
  72,
  11,
  192,
  33,
  15,
  35,
  26,
  70,
  29,
  22,
  46,
  124,
  78,
  16,
  0,
  20,
  13,
  13,
  18,
  18,
  9,
  9,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  30,
  30,
  30,
  30,
  30,
  30,
  30,
  30,
  30]}

Put your parsed results into a DataFrame

In [24]:
fs_df = pd.DataFrame.from_dict(fs_dict)

In [25]:
fs_df

                                 name           address  rating  total ratings
0                       Galaxie Diner   1413 11th St SW     8.7             93
1             Rustic Sourdough Bakery    1305 17 Ave SW     8.5             12
2                      Blanco Cantina     723 17 Ave SW     8.8             36
3                         Caffe Beano      1613 9 St SW     7.9             89
4                               Anejo     723 17 Ave SW     8.5            132
5                          Holy Grill     827 10 Ave SW     8.9             85
6    Trolley 5 Restaurant and Brewery     728 17 Ave SW     8.2             52
7                       Analog Coffee     740 17 Ave SW     8.0            184
8                       Bridgette Bar     739 10 Ave SW     8.4             29
9                  Jamesons Irish Pub  1230 17th Ave SW     7.4             72
10            Sucre Patisserie & Cafe      1007 8 St SW     8.0             11
11                  Ship & Anchor Pub     534 17 Ave SW     8.3            192
12                 Bonterra Trattoria      1016 8 St SW     8.0             33
13                  Casbah Restaurant     720 11 Ave SW     8.1             15
14                    Good Earth Cafe     1502 11 St SW     7.1             35
15                           Thai Tai   615 17th Ave SW     7.9             26
16       Pig & Duke Neighbourhood Pub    1312 12 Ave SW     7.6             70
17                   Philosafy Coffee     632 17 Ave SW     7.8             29
18      Golden Bell Saigon Restaurant    1112 17 Ave SW     6.9             22
19                      Boudoir Rouge      907 9 Ave SW     7.6             46
20                 National Beer Hall     550 17 Ave SW     7.6            124
21               World Bier Haus 1410    1410 17 Ave SW     7.1             78
22               Midori Japanese Cafe    1054 17 Ave SW     6.4             16
23         Popeye's Louisiana Kitchen    1304 17 Ave SW     6.5              0
24                     A&W Restaurant     1320 14 St SW     6.7             20
25              Mugs Restaurant & Pub    1330 15 Ave SW     6.6             13
26                         Fire N Ice     854 16 Ave SW     6.5             13
27            Watchman's Pub & Eatery    1109 17 Ave SW     5.9             18
28                King's Chinese Food    1050 17 Ave SW     0.0             18
29                          Donna Mac      1002 9 St SW     6.2              9
30                    Lounge Eighteen    1005 17 Ave SW     0.0              9
31                        Tim Hortons     539 17 Ave SW     6.3              3
32             Trio Restaurant & Cafe    1504 16 Ave SW     0.0              3
33          Ke Charcoal Grill & Sushi    1501 15 Ave SW     0.0              3
34              Société Coffee Lounge    1223 11 Ave SW     0.0              3
35                     Domino's Pizza      1230 8 St SW     0.0              3
36                     Phil's on 11th    1239 11 Ave SW     0.0              3
37       Alumni Sandwich & Liquor Bar     725 17 Ave SW     0.0              3
38                         Ben's Cafe     909 11 Ave SW     0.0              3
39                       Una Takeaway     616 17 Ave SW     0.0              3
40                       Wakado Ramen     907 10 Ave SW     0.0              3
41                         McDonald's    1422 17 Ave SW     5.0             30
42              Comery Block Barbecue     638 17 Ave SW     0.0             30
43                    Ranchmen's Club     710 13 Ave SW     0.0             30
44                               5S17  634A 17th Ave SW     0.0             30
45         Max Pasley Enterprises Ltd    1032 17 Ave SW     0.0             30
46  Los Chilitos Taco & Tequila House    1309 17 Ave SW     0.0             30
47                      Tsuki Izakaya     908 17 Ave SW     0.0             30
48                      Sultan's Tent     909 17 Ave SW     0.0             30
49      Manie S Pizzeria & Greek Csne     907 17 Ave NW     0.0             30

# Yelp

Send a request with the same location paramaters (location, radius, etc)

In [26]:
y_url = f'https://api.yelp.com/v3/businesses/search?latitude=51.03798628905197&longitude=-114.08773188686932&radius=1000&categories=restaurants&limit=50'
headers = {
    "Authorization": f'Bearer {yelp_key}'
}

In [27]:
res = re.get(y_url, headers=headers)

In [28]:
y_res = res.json()

Parse through your result and get POI details

In [29]:
y_dict = {'name': [],
           'address': [],
           'rating': [],
          'total ratings': []}
for businesses in y_res['businesses']:
    name_value = businesses['name']
    y_dict['name'].append(name_value)
    address_value = businesses['location']['address1']
    y_dict['address'].append(address_value)
    rating_value = businesses['rating']
    rating_value = int(rating_value*2)
    y_dict['rating'].append(rating_value)
    t_ratings_value = businesses['review_count']
    t_ratings_value = int(t_ratings_value)
    y_dict['total ratings'].append(t_ratings_value)

Put your parsed results into a DataFrame

In [31]:
y_df = pd.DataFrame.from_dict(y_dict)

In [32]:
y_df

,name,address,rating,total ratings
0,The Coup,924 17th Avenue SW,8,251
1,Galaxie Diner,1413 11 Street SW,9,125
2,Khao San Thai Kitchen,1314-17 Avenue SW,9,111
3,UNA Pizza + Wine,618 17th Avenue SW,8,367
4,The Holy Grill,827 10th Avenue SW,9,183
5,Analog Coffee,740 17th Avenue SW,8,161
6,Alumni Sandwich & Liquor Bar,725 17 Ave SW,9,62
7,Ke Charcoal Grill & Sushi,1501 15th Avenue SW,9,73
8,Tamarind Vietnamese Grill & Noodle House,908 12 Ave SW,9,83
9,Nami Sushi and Grill,1604 14 Street SW,8,88
10,Posto Pizzeria and Bar,1014 8 St SW,9,86
11,Heaven Restaurant Bar,1013 17 Avenue SW,8,55
12,Gaga Pizzeria,1236 12 Avenue SW,9,57
13,Bridgette Bar,739 10 Avenue SW,9,83
14,Caffe Beano,1613 9 Street SW,8,84
15,Moti Mahal,1805 14 Street SW,8,95
16,Shawarma Knight,1512 14 St SW,9,48
17,Buon Giorno Ristorante Italiano,823 17 Avenue SW,8,72
18,Trolley 5,728 17th Avenue SW,8,115
19,Monki Breakfastclub & Bistro,1301 10 Ave SW,7,187
20,Nikos Pizza,1405 11 Street SW,8,46
21,Rustic Sourdough Bakery,1305 17 Avenue SW,9,29
22,Midori Japanese Cafe,1054 17 Avenue SW,7,53
23,Last Best Brewing & Distilling,607 11 Avenue SW,8,106
24,Ship & Anchor Pub,534 17 Avenue SW,8,143
25,Sucre Patisserie & Cafe,1007 8 Street SW,9,39
26,Universe,1415 17 Avenue SW,8,47
27,Cluck N Cleaver,1511 14th Street SW,8,88
28,Chilitos Taberna,1309 17 Ave SW,7,108
29,Myhre's Deli,1411 11 Street SW,8,41
30,Golden Bell Saigon,1112 17 Avenue SW,8,32
31,Clive Burger,736 17 Ave SW,7,143
32,Bonterra Trattoria,1016 8 Street SW,8,92
33,Pure Modern Asian Kitchen + Bar,815 8 Avenue SW,9,69
34,Damascus,4-718 17th Avenue SW,9,41
35,La Casa Latina Mexican & Latin Grill,101-1324 11 Ave SW,9,30
36,Redheads Japa Cafe,638 11th Avenue SW,8,68
37,Abyssinia Restaurant,910 12 Avenue SW,9,23
38,Las Canarias,1129 17 Avenue SW,8,29
39,Escoba Bistro & Wine Bar,624 8th Avenue SW,9,59
40,Co Do Vietnamese Restaurant,1411 – 17 Avenue SW,7,59
41,South Silk Road Chinese Restaurant,1130 10 Ave SW,8,36
42,Taste Of Korea,1204 17 Ave SW,10,9
43,Vegan Street,1111 7 Street SW,10,15
44,Paros Real Greek,1436 8 Street SW,9,18
45,Kanpai Sushi On 8th,110-1414 8th Street SW,8,29
46,Tuk Tuk Thai,636 17 Avenue SW,7,69
47,Mirchi Restaurant,101 - 825 12th Avenue SW,7,61
48,Hankki,1058 17 Avenue Sw,9,11
49,Banh Mi Thai Tai,615 17 Avenue SW,8,52

# Google (stretch)

Use the same process as the first two APIs

In [33]:
url = f'https://maps.googleapis.com/maps/api/place/textsearch/json?location=51.03798628905197,-114.08773188686932&radius=1000&key={google_key}'

In [6]:
#locationBias: {radius: 1000, center: {lat: 51.03798628905197, lng: -114.08773188686932}}

In [43]:
url = f"https://maps.googleapis.com/maps/api/place/textsearch/json?query=restaurant&location=51.03798628905197,-114.08773188686932&radius=1000&key={google_key}"

payload={}
headers = {}

response = re.request("GET", url, headers=headers, data=payload)

In [44]:
g_res = response.json()

In [45]:
g_dict = {'name': [],
           'address': [],
           'rating': [],
          'total ratings': []}
for results in g_res['results']:
    name_value = results['name']
    g_dict['name'].append(name_value)
    address_value = results['formatted_address']
    g_dict['address'].append(address_value)
    rating_value = results['rating']
    rating_value = float(rating_value * 2)
    g_dict['rating'].append(rating_value)
    t_ratings_value = results['user_ratings_total']
    t_ratings_value = int(t_ratings_value)
    g_dict['total ratings'].append(t_ratings_value)

In [46]:
g_df = pd.DataFrame.from_dict(g_dict)

In [47]:
g_df

,name,address,rating,total ratings
0,Bonterra Trattoria,"1016 8 St SW, Calgary, AB T2R 1K2, Canada",8.6,779
1,Buon Giorno Ristorante Italiano,"823 17 Ave SW, Calgary, AB T2T 0A1, Canada",9.0,772
2,Via Cibo,"1520 14 St SW, Calgary, AB T3C 1C9, Canada",8.4,490
3,Shawarma House Calgary,"555 11 Ave SW, Calgary, AB T2R 1P6, Canada",9.2,325
4,Universe Restaurant,"1415 17 Ave SW A, Calgary, AB T2T 0C6, Canada",9.0,277
5,Posto Pizzeria & Bar,"1014 8 St SW, Calgary, AB T2R 1K2, Canada",9.2,717
6,Donna Mac,"1002 9 St SW, Calgary, AB T2R 0B5, Canada",9.0,551
7,Moxies Calgary Downtown Restaurant,"888 7 Ave SW, Calgary, AB T2P 3J3, Canada",8.0,625
8,Damascus Fine Mediterranean Foods,"718 17 Ave SW #4, Calgary, AB T2S 0B7, Canada",9.6,1107
9,Holy Grill,"827 10 Ave SW, Calgary, AB T2R 0B4, Canada",9.2,963
10,La Casa Latina Restaurant Calgary,"1324 11 Ave SW #101, Calgary, AB T3C 0M6, Canada",9.0,490
11,mashallah restaurant downtown,"1439 17 Ave SW, Calgary, AB T2T 0C8, Canada",10.0,19
12,Paros Real Greek,"1436 8 St SW, Calgary, AB T2R 1R7, Canada",9.2,392
13,Bridgette Bar,"739 10 Ave SW, Calgary, AB T2R 0B3, Canada",9.4,1971
14,Blanco Cantina,"723 17 Ave SW, Calgary, AB T2S 0B6, Canada",8.2,1286
15,Trio Restaurant & Cafe,"1504 16 Ave SW, Calgary, AB T3C 0Z8, Canada",9.0,759
16,HABESHA RESTAURANT,"1039 17 Ave SW, Calgary, AB T2T 0A9, Canada",8.8,107
17,Comery Block Barbecue,"638 17 Ave SW, Calgary, AB T2S 0B4, Canada",9.0,880
18,Alibaba Kabob House Inc,"1602 14 St SW, Calgary, AB T2T 0C3, Canada",8.8,351
19,Galaxie Diner,"1413 11 St SW, Calgary, AB T2R 1G7, Canada",9.4,1359

# Database

Get the top 10 restaurants according to their rating

In [ ]:
#getting foursquare top ten with api specificications

In [48]:
url = f'https://api.foursquare.com/v3/places/search?ll=51.03798628905197,-114.08773188686932&radius=1000&categories=13065&fields=name,location,rating,stats&sort=RATING'
headers = {
    "Accept": "application/json",
    "Authorization": fs_key
}

In [49]:
res = re.request("GET", url, headers=headers)

In [50]:
fs_res = res.json()
fs_dict = {'name': [],
           'address': [],
           'rating': [],
          'total ratings': []}

for result in fs_res['results']:
    name_value = result['name']
    fs_dict['name'].append(name_value)
    address_value = result['location']['address']
    fs_dict['address'].append(address_value)
    rating_value = result['rating']
    rating_value = float(rating_value)
    fs_dict['rating'].append(rating_value)
    t_ratings_value = result['stats']['total_ratings']
    t_ratings_value = int(t_ratings_value)
    fs_dict['total ratings'].append(t_ratings_value)
fst_df = pd.DataFrame.from_dict(fs_dict) 
fst_df

                               name          address  rating  total ratings
0                        Holy Grill    827 10 Ave SW     8.9             85
1                    Blanco Cantina    723 17 Ave SW     8.8             36
2                     Galaxie Diner  1413 11th St SW     8.7             93
3                      Myhre's Deli  1401A1 11 St SW     8.6             19
4                             Anejo    723 17 Ave SW     8.5            132
5           Rustic Sourdough Bakery   1305 17 Ave SW     8.5             12
6                     Bridgette Bar    739 10 Ave SW     8.4             29
7                 Ship & Anchor Pub    534 17 Ave SW     8.3            192
8  Trolley 5 Restaurant and Brewery    728 17 Ave SW     8.2             52
9           Sucre Patisserie & Cafe     1007 8 St SW     8.0             11

In [ ]:
#getting yelp top ten with api specificications (ranking based on yelp weighting)

In [51]:
y_url = f'https://api.yelp.com/v3/businesses/search?latitude=51.03798628905197&longitude=-114.08773188686932&radius=1000&categories=restaurants&limit=10&sort_by=rating'
headers = {
    "Authorization": f'Bearer {yelp_key}'
}

In [52]:
res = re.get(y_url, headers=headers)

In [53]:
y_res = res.json()
y_dict = {'name': [],
           'address': [],
           'rating': [],
          'total ratings': []}
for businesses in y_res['businesses']:
    name_value = businesses['name']
    y_dict['name'].append(name_value)
    address_value = businesses['location']['address1']
    y_dict['address'].append(address_value)
    rating_value = businesses['rating']
    rating_value = int(rating_value*2)
    y_dict['rating'].append(rating_value)
    t_ratings_value = businesses['review_count']
    t_ratings_value = int(t_ratings_value)
    y_dict['total ratings'].append(t_ratings_value)

yt_df = pd.DataFrame.from_dict(y_dict)
yt_df

,name,address,rating,total ratings
0,Alumni Sandwich & Liquor Bar,725 17 Ave SW,9,62
1,Galaxie Diner,1413 11 Street SW,9,125
2,Bridgette Bar,739 10 Avenue SW,9,83
3,Gaga Pizzeria,1236 12 Avenue SW,9,57
4,Khao San Thai Kitchen,1314-17 Avenue SW,9,111
5,The Coup,924 17th Avenue SW,8,251
6,The Holy Grill,827 10th Avenue SW,9,183
7,Tamarind Vietnamese Grill & Noodle House,908 12 Ave SW,9,83
8,Ke Charcoal Grill & Sushi,1501 15th Avenue SW,9,73
9,UNA Pizza + Wine,618 17th Avenue SW,8,367

Put all your results in an SQLite3 database (remember, SQLite stores its databases as files in your local machine - make sure to create your database in your project's data/ directory!)

In [66]:

file = "C:/Users/Alex/lighthouse-data-notes/mini-project-2/mini-project-2/data/streets.db"
connection = sqlite3.connect(file)

In [67]:
c = connection.cursor()

In [68]:
c.execute('''
          CREATE TABLE IF NOT EXISTS google_results
          ([index] INTEGER PRIMARY KEY, [name] TEXT, [address] TEXT, [rating] FLOAT, [total_ratings] INTEGER)
          ''')
          
c.execute('''
          CREATE TABLE IF NOT EXISTS yelp_results
          ([index] INTEGER PRIMARY KEY, [name] TEXT, [address] TEXT, [rating] FLOAT, [total_ratings] INTEGER)
          ''')

c.execute('''
          CREATE TABLE IF NOT EXISTS foursquare_results
          ([index] INTEGER PRIMARY KEY, [name] TEXT, [address] TEXT, [rating] FLOAT, [total_ratings] INTEGER)
          ''')                     
connection.commit()

In [69]:
g_df.to_sql('google_results', connection, if_exists='replace', index = False)

20

In [70]:
fs_df.to_sql('foursquare_results', connection, if_exists='replace', index = False)
y_df.to_sql('yelp_results', connection, if_exists='replace', index = False)

50

In [71]:
connection.close()

# Travelling Salesman Problem (stretch)

If you have time, follow the steps in the [ortools tutorial](https://developers.google.com/optimization/routing/tsp) using Google's [Directions API](https://developers.google.com/maps/documentation/directions/start).

In [1]:
from ortools.linear_solver import pywraplp
from ortools.init import pywrapinit
from ortools.constraint_solver import pywrapcp

In [2]:
def create_data_model():
    """Stores the data for the problem."""
    data = {}
    data['distance_matrix'] = [
        [0, 2451, 713, 1018, 1631, 1374, 2408, 213, 2571, 875, 1420, 2145, 1972],
        [2451, 0, 1745, 1524, 831, 1240, 959, 2596, 403, 1589, 1374, 357, 579],
        [713, 1745, 0, 355, 920, 803, 1737, 851, 1858, 262, 940, 1453, 1260],
        [1018, 1524, 355, 0, 700, 862, 1395, 1123, 1584, 466, 1056, 1280, 987],
        [1631, 831, 920, 700, 0, 663, 1021, 1769, 949, 796, 879, 586, 371],
        [1374, 1240, 803, 862, 663, 0, 1681, 1551, 1765, 547, 225, 887, 999],
        [2408, 959, 1737, 1395, 1021, 1681, 0, 2493, 678, 1724, 1891, 1114, 701],
        [213, 2596, 851, 1123, 1769, 1551, 2493, 0, 2699, 1038, 1605, 2300, 2099],
        [2571, 403, 1858, 1584, 949, 1765, 678, 2699, 0, 1744, 1645, 653, 600],
        [875, 1589, 262, 466, 796, 547, 1724, 1038, 1744, 0, 679, 1272, 1162],
        [1420, 1374, 940, 1056, 879, 225, 1891, 1605, 1645, 679, 0, 1017, 1200],
        [2145, 357, 1453, 1280, 586, 887, 1114, 2300, 653, 1272, 1017, 0, 504],
        [1972, 579, 1260, 987, 371, 999, 701, 2099, 600, 1162, 1200, 504, 0],
    ]  # yapf: disable
    data['num_vehicles'] = 1
    data['depot'] = 0
    return data

In [3]:
data = create_data_model()
manager = pywrapcp.RoutingIndexManager(len(data['distance_matrix']),
                                       data['num_vehicles'], data['depot'])
routing = pywrapcp.RoutingModel(manager)